apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  containers:
  - name: frontend-container
    image: kegodefelix/frontend-app:1.0.0
    ports:
      - containerPort: 3000
        name: frontend