apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - name: "frontend-service"
    port: 3000
    targetPort: 3000
    nodePort: 31000
  selector: 
    app: frontend