version: '3.7'

services:

  mongo:
    container_name: mongo-database
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - my-products:/data/db
    networks:
      - ecommerce-network

  backend-container:
    container_name: backend-container
    image: kegodefelix/backend-app:1.0.0
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/yolomy
    depends_on:
      - mongo
    networks:
      - ecommerce-network

  frontend-container:
    container_name: frontend-container
    image: kegodefelix/frontend-app:1.0.0
    build:
      context: ./client
    ports:
      - "3000:3000"
    # restart: always
    environment:
        BACKEND_HOST: http://backend-container
        NODE_OPTIONS: --openssl-legacy-provider
    depends_on:
        - backend-container
    networks:
        - ecommerce-network


networks:
  ecommerce-network:
    driver: bridge

volumes:
  my-products:



