apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: frontend-container
    image: kegodefelix/backend-app:1.0.0
    ports:
      - containerPort: 5000
        name: backend