apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2-csi
  resources:
    requests:
      storage: 10Gi
